[[main]]
none = "none"

[[main]]
name = "/"
pageRef = "/"
weight = 10

[[main]]
name = "/posts"
pageRef = "posts"
weight = 11

[[main]]
name = "/useful"
pageRef = "useful"
weight = 12

[[main]]
name = "/learning-material"
pageRef = "/education"
weight = 9_999

[[footer]]
none = "none"
