[[main]]
none = "none"

[[main]]
name = "/"
pageRef = "/"
identifier = "ilc5G7Ndcy"
weight = 9_999

[[main]]
name = "/posts"
pageRef = "posts"
identifier = "V1LGWN2iGC"
weight = 9_999

[[footer]]
none = "none"
